# Generated by Django 5.0.4 on 2025-04-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('scientific_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('size', models.CharField(max_length=50)),
                ('plant_type', models.CharField(max_length=50)),
                ('image_url', models.URLField(max_length=500)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=255)),
                ('fee', models.FloatField()),
            ],
        ),
    ]
