# Generated by Django 5.0.4 on 2025-05-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
